kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: microsoft/dotnet:2.0-sdk
    environment:
      NUGETKEY:
        from_secret: NUGET_KEY
    commands:
      - dotnet build Zavolokas.Structures -c Release
      - dotnet test Zavolokas.Structures.UnitTests
    when:
      event: [push]

  - name: publish-structures-nuget
    image: microsoft/dotnet:2.0-sdk
    environment:
      NUGETKEY:
        from_secret: NUGET_KEY
    commands:
      - dotnet build Zavolokas.Structures -c Release
      - dotnet pack Zavolokas.Structures -c Release -p:PackageVersion=2.0.0.$${DRONE_BUILD_NUMBER}
      - dotnet nuget push Zavolokas.Structures/bin/Release/Zavolokas.Structures.2.0.0.$${DRONE_BUILD_NUMBER}.nupkg -s https://api.nuget.org/v3/index.json -k $${NUGETKEY}
    when:
      event: [tag]
      branch: [master]
  
  - name: publish-structures-gdi-nuget
    image: microsoft/dotnet:2.0-sdk
    environment:
      NUGETKEY:
        from_secret: NUGET_KEY
    commands:
      - dotnet build Zavolokas.Structures.Gdi -c Release
      - dotnet pack Zavolokas.Structures.Gdi -c Release -p:PackageVersion=2.0.0.$${DRONE_BUILD_NUMBER}
      - dotnet nuget push Zavolokas.Structures.Gdi/bin/Release/Zavolokas.Structures.Gdi.2.0.0.$${DRONE_BUILD_NUMBER}.nupkg -s https://api.nuget.org/v3/index.json -k $${NUGETKEY}
    when:
      event: [tag]
      branch: [master]